### ISSUE TITLE
incsrc with subfolders is still weird when specifying the file to assemble relatively

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#45] opened 2018-03-30 17:27 UTC
[see here](https://smwc.me/1466881)
Also the test suite's incsrc test fails when specifying some paths (namely the folder where to find tests) relatively (all other tests work fine, i assume it's because the given path is added as a search path but the asm files to compile will be somewhere else where the relative path isn't valid anymore).
Interestingly these issues don't happen when the base file to assemble is specified absolutely.

**Comment by RPGHacker** [comment] 2018-03-30 17:34
Assigning to myself (think I already know what the cause of this problem is).

**Comment by RPGHacker** [comment] 2018-03-30 17:34
Btw., we should totally use the "assign" function on GitHub more so that we don't accidentally both end up working on the same stuff.

**Comment by randomdude999** [comment] 2018-03-30 17:36
I would but I can't assign myself to issues since i'm not a collaborator. If you made me one then I could also push to the repo but I promise I'll still do my stuff in feature branches. (and I could also add labels and stuff to issues)

**Comment by RPGHacker** [comment] 2018-03-30 17:38
Sounds reasonable (I wasn't aware you need to be a collaborator for assigning to work). Give me a bit, I will check collaborator stuff out. Until then, I guess you can just leave comments on an issue and I can assign it to you.

**Closed** 2018-03-30 21:45 UTC
