### ISSUE TITLE
defined(sa1) == 0 is not working

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#169] opened 2020-08-18 09:50 UTC
There’s is a problem during development of my screen Scrolling Pipes pipes: (https://github.com/GhbSmwc/SMB3_ScreenScrollingPipes ) defines file (to change settings and what freeram to use, sa1 remapping defines is commented out and located near the top) that I cannot use this feature to check if ‘!sa1’ is already defined or not. It errors out in Uberasm tool saying “invalid number”.

**Comment by RPGHacker** [comment] 2020-08-18 10:09
I think it needs to be `defined("sa1")`
Not sure if p4plus2's pull request that was recently merged changes this, but I think that pull request was only for the sizeof() function. I think most functions still require the double quotes.

**Comment by GhbSmwc** [comment] 2020-08-18 10:16
I did, see here: https://github.com/GhbSmwc/SMB3_ScreenScrollingPipes/blob/master/SSPDef/Defines.asm

**Comment by RPGHacker** [comment] 2020-08-18 10:26
So
```if defined("sa1") == 0```
this throws the "invalid number" error?

**Comment by GhbSmwc** [comment] 2020-08-18 10:31
Yes.

**Comment by randomdude999** [comment] 2020-08-18 11:47
i can't reproduce this. can you please post a patch that when applied to a clean smw rom throws this error

**Comment by GhbSmwc** [comment] 2020-08-18 23:41
Wait, I'm testing this on UberasmTool v1.1! That might be using an older version of asar. UberasmTool version 1.3 uses Asar v.1.61

Tested using the newer version of uberasm tool and no bug was found.

**Closed** 2020-08-18 23:56 UTC
